package com.hoavd.fbstore.common.constants;

public interface ResponseMessageConstants {
  //SYSTEM
  String ERROR = "MSG_ERROR";
  String ERR_SYSTEM = "MSG_ERROR_SYSTEM";
  String INFORMATION_INVALID = "MSG_INFORMATION_INVALID";
  String AUTHENTICATION_EXCEPTION = "MSG_AUTHENTICATION_EXCEPTION";

  //LOGIN
  String LOGIN_SUCCESS = "MSG_LOGIN_SUCCESS";
  String TOKEN_EXPIRED = "MSG_TOKEN_EXPIRED";
  String TOKEN_INVALID = "MSG_TOKEN_INVALID";
  String LOGIN_REFRESH_EXCEPTION = "MSG_LOGIN_REFRESH_EXCEPTION";

  //ADMIN
  String ADMIN_DOES_NOT_EXIST = "MSG_ADMIN_DOES_NOT_EXIST";
  String EMAIL_ALREADY_EXIST = "MSG_EMAIL_ALREADY_EXIST";
  String CREATE_ACC_ADMIN_SUCCESS = "MSG_CREATE_ACC_ADMIN_SUCCESS";
  String UPDATE_ACC_ADMIN_SUCCESS = "MSG_UPDATE_ACC_ADMIN_SUCCESS";
  String DELETE_ACC_ADMIN_SUCCESS = "MSG_DELETE_ACC_ADMIN_SUCCESS";

  //USER
  String USERNAME_ALREADY_EXIST = "MSG_USERNAME_ALREADY_EXIST";
  String USER_DOES_NOT_EXIST = "MSG_USER_DOES_NOT_EXIST";
  String CREATE_ACC_USER_SUCCESS = "MSG_CREATE_ACC_USER_SUCCESS";
  String UPDATE_ACC_USER_SUCCESS = "MSG_UPDATE_ACC_USER_SUCCESS";
  String DELETE_ACC_USER_SUCCESS = "MSG_DELETE_ACC_USER_SUCCESS";

  //CATEGORY
  String CATEGORY_NAME_ALREADY_EXIST = "MSG_CATEGORY_NAME_ALREADY_EXIST";
  String CATEGORY_DOES_NOT_EXIST = "MSG_CATEGORY_DOES_NOT_EXIST";
  String CREATE_CATEGORY_SUCCESS = "MSG_CREATE_CATEGORY_SUCCESS";
  String UPDATE_CATEGORY_SUCCESS = "MSG_UPDATE_CATEGORY_SUCCESS";
  String DELETE_CATEGORY_SUCCESS = "MSG_DELETE_CATEGORY_SUCCESS";

  //PRODUCER
  String PRODUCER_NAME_ALREADY_EXIST = "MSG_PRODUCER_NAME_ALREADY_EXIST";
  String PRODUCER_DOES_NOT_EXIST = "MSG_PRODUCER_DOES_NOT_EXIST";
  String CREATE_PRODUCER_SUCCESS = "MSG_CREATE_PRODUCER_SUCCESS";
  String UPDATE_PRODUCER_SUCCESS = "MSG_UPDATE_PRODUCER_SUCCESS";
  String DELETE_PRODUCER_SUCCESS = "MSG_DELETE_PRODUCER_SUCCESS";

  //PRODUCT
  String PRODUCT_NAME_ALREADY_EXIST = "MSG_PRODUCT_NAME_ALREADY_EXIST";
  String PRODUCT_DOES_NOT_EXIST = "MSG_PRODUCT_DOES_NOT_EXIST";
  String CREATE_PRODUCT_SUCCESS = "MSG_CREATE_PRODUCT_SUCCESS";
  String UPDATE_PRODUCT_SUCCESS = "MSG_UPDATE_PRODUCT_SUCCESS";
  String DELETE_PRODUCT_SUCCESS = "MSG_DELETE_PRODUCT_SUCCESS";

  //PROMOTION
  String PROMOTION_NAME_ALREADY_EXIST = "MSG_PROMOTION_NAME_ALREADY_EXIST";
  String PROMOTION_DOES_NOT_EXIST = "MSG_PROMOTION_DOES_NOT_EXIST";
  String CREATE_PROMOTION_SUCCESS = "MSG_CREATE_PROMOTION_SUCCESS";
  String UPDATE_PROMOTION_SUCCESS = "MSG_UPDATE_PROMOTION_SUCCESS";
  String DELETE_PROMOTION_SUCCESS = "MSG_DELETE_PROMOTION_SUCCESS";

  String PROMOTION_PRODUCT_DOES_NOT_EXIST = "MSG_PROMOTION_DOES_NOT_EXIST";
  String CREATE_PROMOTION_PRODUCT_SUCCESS = "MSG_CREATE_PROMOTION_PRODUCT_SUCCESS";
  String REMOVE_PROMOTION_PRODUCT_SUCCESS = "MSG_REMOVE_PROMOTION_PRODUCT_SUCCESS";
}
